server:
  port: 8085

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_dxh?serverTimezone=UTC
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
#  freemarker:
#    suffix: .ftl
#    charset: UTF-8
#    content-type: text/html
#    template-loader-path: classpath:/templates

mybatis:
  mapper-locations: classpath:com/gs/mapper/*Mapper.xml
  type-aliases-package: com.gs.bean
